# Generated by Django 5.0.1 on 2024-02-19 13:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
