# Generated by Django 5.0.1 on 2024-02-19 13:11

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ielts_choice', models.CharField(choices=[('5-5.5', '5-5.5'), ('6-6.5', '6-6.5'), ('7-7.5', '7-7.5'), ('8-8.5', '8-8.5'), ('9', '9'), ('No', 'No')], default='6-6.5', max_length=255)),
                ('math_choice', models.CharField(choices=[('Foundation', 'Foundation'), ('High', 'High'), ('SAT', 'SAT'), ('No', 'No')], default='SAT', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(upload_to='university/')),
                ('ielts', models.FloatField(default=0.0)),
                ('sat', models.IntegerField(default=0)),
                ('gpa', models.FloatField(default=0.0)),
                ('scholarship_count', models.PositiveIntegerField()),
                ('acceptance_rate', models.IntegerField()),
                ('in_the_world', models.IntegerField()),
                ('fee', models.CharField(max_length=255)),
                ('requirements', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.location')),
                ('majors', models.ManyToManyField(to='university.major')),
                ('subjects', models.ManyToManyField(to='university.subject')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
