# Generated by Django 5.0.1 on 2024-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='wallpaper',
            field=models.ImageField(blank=True, upload_to='university/'),
        ),
    ]
