# Generated by Django 5.0.1 on 2024-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0002_university_wallpaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="location_type",
            field=models.CharField(
                choices=[("Domestic", "Domestic"), ("International", "International")],
                default="International",
                max_length=255,
            ),
        ),
    ]
