# Generated by Django 5.0.1 on 2024-04-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_coin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="coin",
            field=models.IntegerField(default=200),
        ),
    ]
