# Generated by Django 5.0.1 on 2024-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_coin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="coin",
            field=models.IntegerField(default=20),
        ),
    ]
