# Generated by Django 5.0.1 on 2024-05-16 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0003_university_location_type"),
        ("users", "0004_alter_user_coin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="english_score",
            field=models.CharField(
                choices=[
                    ("5-5.5", "5-5.5"),
                    ("6-6.5", "6-6.5"),
                    ("7-7.5", "7-7.5"),
                    ("8-8.5", "8-8.5"),
                    ("9", "9"),
                    ("No", "No"),
                ],
                default="6-6.5",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hobby",
            field=models.CharField(default="math", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="major",
            field=models.ForeignKey(
                default=193,
                on_delete=django.db.models.deletion.CASCADE,
                to="university.major",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="math_score",
            field=models.CharField(
                choices=[
                    ("Foundation", "Foundation"),
                    ("High", "High"),
                    ("SAT", "SAT"),
                    ("No", "No"),
                ],
                default="SAT",
                max_length=255,
            ),
        ),
    ]
