version: "3"
services:
  postgres-service:
    image: postgres:13.3
    restart: always
    container_name: "${PROJECT_NAME}-postgres"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - univway-db:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

  redis:
    image: redis:7.2.4
    container_name: "${PROJECT_NAME}-redis"
    ports:
      - 6379:6379

volumes:
  univway-db:
    driver: local

